# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JaCo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'JSONtoCodable'

  # Pods for JaCo

  target 'JaCoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JaCoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
